version: "3"
services:
  frontend_server:
    image: hyeeeeejin/condibook-front:0.0.6
    restart: "on-failure"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - condibook

  certbot:
    image: certbot/certbot:latest
    restart: "on-failure"
    depends_on:
      - frontend_server
    command: certonly --webroot --webroot-path=/var/www/certbot --email hjeom.dev@gmail.com --agree-tos --no-eff-email -d kdt-ai4-team14.elicecoding.com
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt

  backend_server:
    image: hyeeeeejin/condibook-back:0.0.6
    restart: "on-failure"
    ports:
      - 5001:5001
    networks:
      - condibook

  ai_server:
    image: hyeeeeejin/condibook-ai:0.0.5
    restart: "on-failure"
    ports:
      - 5004:5004
    networks:
      - condibook

networks:
  condibook:
